version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - gosec

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - fmt.Sscanf
        - time.Parse
        - json.Marshal
        - io.ReadAll
        - os.Setenv
        - os.Unsetenv
        - os.Remove
        - os.RemoveAll
        - (http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
    gosec:
      excludes:
        - G104
        - G204
        - G115
        - G306
        - G301
        - G304
    govet:
      disable:
        - fieldalignment
        - shadow
    staticcheck:
      checks:
        - all
        - "-SA1019"
